### ISSUE TITLE
User databases shouldn't share a global namespace

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/socket-pouch#1]
If two users each request a database named `'foo'`, it'd be silly for them to share it. Unless you really wanted that, which seems unlikely to me.

The default should probably be that user databases are separated by `socket.id` so that they can't be shared. I.e. one-db-per-user is the default.

Of course there's also db-per-role to consider, and maybe some devs will want their users to share a global database and do some fancy filtered replication. So the API should be flexible enough to handle all cases.

**Comment by tcoats** [comment]
Is this already handled by the server because `pouchCreator` is called per socket and saved against `'$' + socket.id`?
https://github.com/nolanlawson/socket-pouch/blob/master/lib/server/index.js#L195

**Comment by nolanlawson** [comment]
No, because the default PouchCreator will still use the same name for both, meaning they will use the same database under the hood. OTOH users can easily override this, so I'm going to close this issue as unimportant.
