### ISSUE TITLE
Attaching to an existing http listener

### ISSUE THREAD

**Issue by coolcorey** [nolanlawson/socket-pouch#11]
So, I have an express web server, and I wanted to add your socket-pouch proxy to that same server. When I decided to implement SSL for the webserver, Chrome complains about a mixed-content page (partially http, and partially https). So instead of making separate listeners for express and socket-pouch, I figured I would make one https server and attach express and socket-pouch to it. I had to update socket-pouch to expose Engine.io's attach function. It works well, and allows you to have socket-pouch and your webserver on the same port with the same certificates.

Now, I have no idea how to github, so, I was thinking I would just give you the simple changes I made and you could integrate them one day.

socket-pouch/lib/server/index.js(roughly line 310):

```
function attach(httpServer, options, callback) {
  if (typeof options === 'function') {
    callback = options;
    options = {};
  }
  options = options || {};
  var server = engine.attach(httpServer, options.socketOptions || {});

  var pouchCreator = makePouchCreator(options);

  server.on('connection', function(socket) {
    socket.on('message', function (message) {
      if (typeof message !== 'string') {
        return onReceiveBinaryMessage(message, socket);
      }
      onReceiveTextMessage(message, socket, pouchCreator);
    }).on('close', function () {
      log('closing socket', socket.id);
      socket.removeAllListeners();
      delete dbs['$' + socket.id];
    }).on('error', function (err) {
      log('socket threw an error', err);
      socket.removeAllListeners();
      delete dbs['$' + socket.id];
    });
  });
}
```

then, exported the function (found at the end of the file)

```
module.exports = {
  listen: listen,
  attach: attach
};
```

then to use this you just do:

```
var fs = require('fs'),
https = require('https'),
express = require('express'),
socketPouchServer = require('socket-pouch/server'),
webServer = express();

var WebServer_PORT = 443;

var sslOpts = {
  key: fs.readFileSync('key.pem'),
  cert: fs.readFileSync('cert.pem')
}

webServer.use(express.static('public'));

var secureListener = https.createServer(sslOpts, webServer).listen(WebServer_PORT);

socketPouchServer.attach(secureListener, {
  remoteUrl: 'http://xxx.xxx.xxx.xxx:5984',
})
```

Hopefully this is taken well, and not seen as a lazy person not wanting to learn how to do the githubz.

**Comment by nolanlawson** [comment]
Kinda responded here: https://github.com/nolanlawson/socket-pouch/pull/12#issuecomment-210921606. Lemme know if I'm wrong, but I think an Apache/Nginx reverse proxy can serve your needs perfectly.

I have some sample code showing how to set this up in Nginx over port 80 at least (although you will definitely want to use 443 for SSL), hopefully that will point you in the right direction: https://nolanlawson.com/2013/05/31/web-sockets-with-socket-io-node-js-and-nginx-port-80-considered-harmful/

**Comment by atsepkov** [comment]
@nolanlawson I too need to attach to existing server, in my case I don't think the reverse-proxy solution would help (but I could be wrong). I'm hosting my app on Heroku, the Nginx/Apache config is not exposed to me, and Heroku limits each app to one port, meaning that I can't launch a WebSocket connection unless it's using the same port as my https connection, and I can't use the same port unless I attach to existing server. This change would make pouchDB (with websockets) usable on Heroku.

**Comment by coolcorey** [comment]
You can use my solution. Socket Pouch is a little of a memory hog. Something to keep in mind.

**Comment by atsepkov** [comment]
I was hoping to combine it with something akin to delta-pouch to reduce the footprint of data sent across and bandwidth, but it seems that project is no longer maintained.
