### ISSUE TITLE
socket-pouch with CouchDB backend - ws:// sync() performance regression over http:// ?

### ISSUE THREAD

**Issue by dharders** [nolanlawson/socket-pouch#19]
I'm a little confused with socket-pouch. I have assumed (naively?) that websocket performance would be faster than http in regards to pouchdb -> couchdb via socket-pouch.

Is socket-pouch meant to improve sync() performance ? Or is it just a little side project to prove that it can be done ?

I'm trying to decide whether to stick with traditional http sync or go the websocket route.

In my (limited) testing, an initial sync using socket-pouch of ~3000 docs took 3x longer than the http equivalent.

**Comment by nolanlawson** [comment]
> Is socket-pouch meant to improve sync() performance ? Or is it just a little side project to prove that it can be done ?

Mostly the latter. Websockets are not some performance magic pixie dust, but they can help in some situations. When loading 3000 docs, a lot of the performance hit will just be IndexedDB readwrite transactions, so whatever network mechanism you use is not going to change much.
