### ISSUE TITLE
How many websockets are using when syncing multiple databases?

### ISSUE THREAD

**Issue by khejing** [nolanlawson/socket-pouch#21]
I'm writing a chat program, so I use one DB per session pattern. If using one DB per user pattern, the database will be more, and the program logic will be harder.

Every user has multiple sessions, so PouchDB will use multiple long polling, this is very resource consuming. I'm just curious about if this library will solve the problem?

**Comment by nolanlawson** [comment]
Each PouchDB object you create that uses the `socket` adapter represents one single web socket. And yes, this sounds like something that can improve performance in your use case, assuming your connection to CouchDB/PouchDB on the server side is still not using too many HTTP connections. Hope that helps!

**Comment by khejing** [comment]
Thanks for your reply!
