### ISSUE TITLE
Recipes for authentication

### ISSUE THREAD

**Issue by bensleveritt** [nolanlawson/socket-pouch#25]
Not sure is this is the best venue for requests like this, but are there any recipes/guidelines/suggestions for access restriction or general authentication/session management with `socket-pouch`?

I've been reading through [`pouchdb-authentication`'s source](https://github.com/nolanlawson/pouchdb-authentication) and gleaning some insight into how authentication can be done over HTTP, and simple things like user/session creation seem pretty portable. I just can't figure out a meaningful authentication method for requests following that.

I'm considering starting a plugin to handle authentication (or supplement `pouchdb-authentication`), but I want to check here first that I'm not missing something.

**Comment by nolanlawson** [comment]
Sorry, I didn't really think this far with socket-pouch. The pouchCreator basically lets you do whatever you want, but for authentication that'd be up to you...

**Comment by bensleveritt** [comment]
No worries, I'll close this, and revisit later when I have some suggestions of my own.

**Comment by atsepkov** [comment]
Hi, I too am interested in this. I tried to use pouchCreator, but I end up with a promise rather than a db handle in the end, which makes all the calls to the db inconvenient afterwards. I went with the authentication approach mentioned in the README.
