### ISSUE TITLE
Does socket-pouch work with the current PouchDB (3.6.0 ?)

### ISSUE THREAD

**Issue by gkovacs** [nolanlawson/socket-pouch#4]
I see on the readme that you said this requires your custom pouchdb branch, and they would hopefully make it to pouchdb by version 3.5.0. Pouchdb is now at 3.6.0, and looking at those 3 commits that are different it seems the associated issues have all been closed. Does it work with pouchdb 3.6.0? Would be very helpful to update the readme accordingly. Thanks!

**Comment by nolanlawson** [comment]
No, the necessary changes didn't all get merged. I'm going to try to get around to it when I get a chance, but for now socket-pouch is kind of in limbo because I've been focusing on other stuff. Sorry about that!

**Comment by nolanlawson** [comment]
In particular there are some changes to mapreduce that would need to be ported over (rebasing is not enough, since mapreduce has since been merged into PouchDB proper): https://github.com/pouchdb/pouchdb/commit/9e56b3a2aeb9b620e6b55489b1f0b99fa30e8429
