### ISSUE TITLE
Error using redisdown

### ISSUE THREAD

**Issue by brandonros** [nolanlawson/socket-pouch#5]
Not sure if this is redisdown related or not, but changing

``` javascript
function addUncaughtErrorHandler(db, socket) {
  return db.then(function (res) {
    res.pouch.on('error', function (err) {
      sendUncaughtError(socket, err);
    });
  });
}
```

to

``` javascript
function addUncaughtErrorHandler(db, socket) {
  return db.pouch.then(function (res) {
    res.on('error', function (err) {
      sendUncaughtError(socket, err);
    });
  });
} 
```

made it work.

**Comment by nolanlawson** [comment]
Putting a `then()` handler on a pouch is deprecated behavior, also I have no idea why Redisdown would behave differently, but I'm 99% sure this is related to https://github.com/pouchdb/express-pouchdb/issues/264

**Comment by nolanlawson** [comment]
Please find steps to repro and re-file if it is indeed a bug in this plugin, but I'm fairly certain it's a bug in redisdown instead.
